apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows user "srihari" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
 name: read-pods
subjects:
- kind: ServiceAccount
  name: test-sa
# YOu can specify more than one "subject"
- kind: User
  name: srihari
  apiGroup: rbac.authorization.k8s.io
roleRef:
# "roleRef" specifies the binding to a Role / ClusterRole

  kind: Role # this must be Role or clusterRole
  name: pod-reader # this must match the name of the Role or clusterRole you wish to bind 
  apiGroup: rbac.authorization.k8s.io
