apiVersion: apps/v1
kind: Deployment
metadata: 
  name: final-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sriimg2
  template:
    metadata:
     labels:
       app: sriimg2
    spec:
      containers:
      - name: my-container
        image: srihari541/sriproject:2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: final-deployment
  labels:
    app: sriimg2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sriimg2
